spring:
    profiles:
        active: dev
        include: native
    devtools:
        restart:
            enabled: true
    cloud:
        config:
            name: itsol-registry
            server:
                native:
                    search-locations: file:./central-config
                prefix: /config
